Add missing include into regress_thread.h
    D:/a/libevent/libevent/test/regress.c: In function 'test_del_wait':
    D:/a/libevent/libevent/test/regress_thread.h:36:34: error: implicit declaration of function '_beginthreadex' [-Wimplicit-function-declaration]
       36 |         uintptr_t threadhandle = _beginthreadex(NULL,0,fn,(arg),0,NULL);  \
          |                                  ^~~~~~~~~~~~~~
    D:/a/libevent/libevent/test/regress.c:1449:9: note: in expansion of macro 'THREAD_START'
     1449 |         THREAD_START(thread, del_wait_thread, NULL);
          |         ^~~~~~~~~~~~

CI: https://github.com/libevent/libevent/actions/runs/23465601156/job/68276939013?pr=1851