ci: proper usage of run-vcpkg@v11
Two arguments was simply ignored

    2026-03-22T15:01:06.2950462Z ##[warning]Unexpected input(s) 'vcpkgArguments', 'vcpkgTriplet', valid inputs are ['vcpkgDirectory', 'runVcpkgInstall', 'vcpkgGitCommitId', 'vcpkgGitURL', 'doNotUpdateVcpkg', 'doNotCache', 'vcpkgJsonGlob', 'vcpkgJsonIgnores', 'vcpkgConfigurationJsonGlob', 'binaryCachePath', 'runVcpkgFormatString', 'useShell', 'logCollectionRegExps']

Which lead to lack of MbedTLS library, and subsequent failures of
TEST_EXPORT_SHARED/STATIC:

    Error:   Your libevent library does not contain a mbedtls component!

(cherry picked from commit 495f09ea3967e009e86673b28f0cab378e9cf321)